#!/usr/bin/expect -f
log_user 1
set timeout 28
set HOSTIP [lindex $argv 0]
set HOSTID [lindex $argv 1]
set HOSTPW [lindex $argv 2]
set PROXYIP [exec ifconfig tun0 | grep "inet addr:" | cut -d: -f2 | awk {{print $1}}]

spawn ssh -q -o StrictHostKeyChecking=no $HOSTID@$HOSTIP
expect "password"
send $HOSTPW\r
expect \\\$
send "echo \"Starting Zabbix automated maintenance script. For details contact gts-is-sl@wwpdl.vnet.ibm.com.\"\r"
expect \\\$
send "su -\r"
expect "assword"
send $HOSTPW\r
expect \\\#
send "echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections\r"
expect \\\#
send "sudo killall zabbix_agentd\r"
expect \\\#
send "service zabbix-agent stop\r"
expect \\\#
send "ln -s /usr/lib/libnetsnmp.so.30 /usr/lib/libnetsnmp.so.15\r"
expect \\\#
send "dpkg -r zabbix-agent --purge\r"
expect \\\#
send "dpkg -r fping --purge\r"
expect \\\#
send "rm -Rf /etc/zabbix/\r"
expect \\\#
send "rm -Rf /tmp/zabbix/\r"
expect \\\#
send "mkdir -p /tmp/zabbix/\r"
expect \\\#
send "cd /tmp/zabbix\r"
expect \\\#
send "if wget http://$PROXYIP:8000/zabbix-agent_2.2.13-1+squeeze_amd64.deb; then dpkg -i zabbix-agent_2.2.13-1+squeeze_amd64.deb; else echo \"error downloading zabbix-agent_2.2.13-1+squeeze_amd64.deb\" && exit; fi\r"
expect {
    "#" {
    }
    "$" {
        exit
    }
}
send "service zabbix-agent stop\r"
expect \\\#
send "if wget http://$PROXYIP:8000/fping_3.2-1_amd64.deb; then dpkg -i fping_3.2-1_amd64.deb; else echo \"error downloading fping_3.2-1_amd64.deb\" && exit; fi\r"
expect {
    "#" {
    }
    "$" {
        exit
    }
}
send "if wget http://$PROXYIP:8000/vyatta.base; then rm -f /etc/zabbix/zabbix_agentd.conf && mv vyatta.base /etc/zabbix/zabbix_agentd.conf; else echo \"error downloading vyatta.base\" && exit; fi\r"
expect {
    "#" {
    }
    "$" {
        exit
    }
}
send "if wget http://$PROXYIP:8000/vyatta_userparams.conf; then mv vyatta_userparams.conf /etc/zabbix/zabbix_agentd.d/vyatta_userparams.conf; else echo \"error downloading vyatta_userparams.conf\" && exit; fi\r"
expect {
    "#" {
    }
    "$" {
        exit
    }
}
send "if wget http://$PROXYIP:8000/peer_discovery.sh; then mv peer_discovery.sh /etc/zabbix/peer_discovery.sh && chmod +x /etc/zabbix/peer_discovery.sh; else echo \"error downloading peer_discovery.sh\" && exit; fi\r"
expect {
    "#" {
    }
    "$" {
        exit
    }
}
send "if wget http://$PROXYIP:8000/peer_discoveryv2.sh; then mv peer_discoveryv2.sh /etc/zabbix/peer_discoveryv2.sh && chmod +x /etc/zabbix/peer_discoveryv2.sh; else echo \"error downloading peer_discoveryv2.sh\" && exit; fi\r"
expect {
    "#" {
    }
    "$" {
        exit
    }
}
send "if wget http://$PROXYIP:8000/gre_discovery.sh; then mv gre_discovery.sh /etc/zabbix/gre_discovery.sh && chmod +x /etc/zabbix/gre_discovery.sh; else echo \"error downloading gre_discovery.sh\" && exit; fi\r"
expect {
    "#" {
    }
    "$" {
        exit
    }
}
send "if wget http://$PROXYIP:8000/vyatta_ipsectunstatus.sh; then mv vyatta_ipsectunstatus.sh /etc/zabbix/vyatta_ipsectunstatus.sh && chmod +x /etc/zabbix/vyatta_ipsectunstatus.sh; else echo \"error downloading vyatta_ipsectunstatus.sh\" && exit; fi\r"
expect {
    "#" {
    }
    "$" {
        exit
    }
}
send "if wget http://$PROXYIP:8000/script-template; then mv script-template /etc/zabbix/script-template && chmod +x /etc/zabbix/script-template; else echo \"error downloading script-template\" && exit; fi\r"
expect {
    "#" {
    }
    "$" {
        exit
    }
}
send "awk '!/Server=/' /etc/zabbix/zabbix_agentd.conf> /tmp/zbx_tmp.conf && mv /tmp/zbx_tmp.conf /etc/zabbix/zabbix_agentd.conf && echo Server=$PROXYIP >> /etc/zabbix/zabbix_agentd.conf\r"
expect \\\#
send "cd /tmp\r"
expect \\\#
send "service zabbix-agent restart\r"
expect \\\#
send "exit\r"
expect \\\$
send "echo \"Zabbix automated maintenance script finished.\"\r"
expect \\\$
send "exit\r"

